### PR TITLE
[LIMINAL-52]: upgrade to airflow 2.1.2

### PR DESCRIPTION
**Pull request by naturalett**

### CODE REVIEW

**Review by aviem-naturalint — COMMENTED** [review]
There are several failing tests

image

**Comment by aviem-naturalint** [comment]
Please open a JIRA ticket and update the PR title with ticket ID

**Comment by naturalett** [comment]
Unittests :white_check_mark:
All three examples :white_check_mark:

**Review by aviemzur — COMMENTED** [review]
Looks great.
Could use a couple of unit tests which test if kube volumes/pvc were created/deleted

**Review by aviemzur — APPROVED** [review]
LGTM

**Pull request merged**
